spring.application.name=rule-engine
spring.datasource.url=jdbc:postgresql://localhost:5432/rule_engine
spring.datasource.username=postgres
spring.datasource.password=Sabesh123

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
